name: Testes Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Verificar versão do Chrome
      run: google-chrome --version

    - name: Rodar os testes com Maven
      run: mvn test
